services:
  - type: web
    name: mi-portafolio
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: CONTACT_TO_EMAIL
        value: abdielmendoza2906@gmail.com
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
